# Generated by Django 3.2 on 2021-12-02 21:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_institucion'),
        ('persona', '0004_alter_datosgenerales_persona'),
    ]

    operations = [
        migrations.CreateModel(
            name='Laboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(max_length=100, verbose_name='Cargo')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('traja_actualmente', models.BooleanField(default=False)),
                ('descripcion_cargo', models.CharField(max_length=250, verbose_name='Descripcion del cargo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='EvaluadorProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiencia', models.CharField(blank=True, choices=[('evaluador', 'Experiencia como Evaluador'), ('formulador', 'Experiencia como formulador(sólo proyectos ganados)')], max_length=45, null=True)),
                ('anio', models.CharField(blank=True, max_length=4, null=True, verbose_name='Año del proyecto')),
                ('tipo_proyecto_formulado', models.CharField(choices=[('incentivos_tributarios', 'Incentivos tributarios'), ('pasantias_misiones', 'Pasantías y/o misiones'), ('desarrollo_industrial', 'Proyecto de desarrollo industrial'), ('equipamiento_cientifico', 'Proyectos de equipamiento científico/tecnológico'), ('extensionismo_tecnologico', 'Proyectos de extensionismo tecnológico'), ('innovacion', 'Proyectos de Innovación'), ('inversion_publica_snip', 'Proyectos de inversión pública-SNIP'), ('investigacion_aplicada', 'Proyectos de investigación aplicada'), ('investigacion_basica', 'Proyectos de investigación básica'), ('transferencia_tecnologia', 'Proyectos de transferencia tecnológica'), ('otros', 'Otros')], max_length=45, verbose_name='Tipo de proyecto formulado')),
                ('metodologia_evaluacion', models.CharField(blank=True, choices=[('evaluador_por_panel', 'Evaluador por panel'), ('evaluador_por_pares', 'Evaluador por pares'), ('evaluador_unico_individual', 'Evaluador único/individual')], max_length=45, null=True, verbose_name='Metodología de evaluación')),
                ('nombre_concurso', models.CharField(max_length=250, verbose_name='Nombre del concurso')),
                ('url_concurso', models.CharField(blank=True, max_length=250, null=True, verbose_name='Url del concurso')),
                ('presupuesto_proyecto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto total del proyecto formulado')),
                ('entidad_financiadora', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('pais', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='DocumentoAdjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(choices=[('laboral', 'Laboral'), ('docente', 'Docente'), ('evaluador_proyecto', 'Evaluador de proyecto'), ('asesor_tesis', 'Asesor de tesis')], max_length=45)),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='persona.persona', verbose_name='informe')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_institucion', models.CharField(choices=[('universidad', 'Universidad'), ('instituto', 'Instituto'), ('otros', 'Otros')], max_length=45)),
                ('tipo_docente', models.CharField(blank=True, choices=[('contratado', 'Contratado'), ('principal', 'Ordinario-Principal'), ('asociado', 'Ordinario-Asociado'), ('auxiliar', 'Ordinario-Auxiliar'), ('extraordinario', 'Extraordinario(emerito, honorario, y similares')], max_length=70, null=True)),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('traja_actualmente', models.BooleanField(default=False)),
                ('descripcion_cargo', models.CharField(max_length=250, verbose_name='Descripcion del cargo')),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
        ),
        migrations.CreateModel(
            name='AsesorTesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tesis', models.CharField(choices=[('doctorado', 'DOCTORADO'), ('magister', 'MAGISTER'), ('licenciado_titulo', 'LICENCIADO/TÍTULO'), ('bachiller', 'BACHILLER'), ('segunda_especialidad', 'SEGUNDA ESPECIALIDAD')], max_length=45)),
                ('tesista', models.CharField(max_length=200, verbose_name='Tesista')),
                ('fecha_aceptacion_tesis', models.DateField(verbose_name='Fecha de aceptación de la tesis')),
                ('enlace_fuente_repositorio_academico', models.CharField(blank=True, max_length=250, null=True, verbose_name='Enlace de Fuente del repositorio académico')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('universidad', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
            ],
        ),
    ]
