# Generated by Django 3.2 on 2021-12-02 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='laboral',
            old_name='traja_actualmente',
            new_name='trabaja_actualmente',
        ),
    ]
