# Generated by Django 3.2 on 2021-12-03 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0002_rename_traja_actualmente_laboral_trabaja_actualmente'),
    ]

    operations = [
        migrations.AddField(
            model_name='docente',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación'),
        ),
        migrations.AddField(
            model_name='docente',
            name='modificado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación'),
        ),
        migrations.AddField(
            model_name='documentoadjunto',
            name='modificado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='evaluadorproyecto',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='evaluadorproyecto',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='evaluadorproyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación'),
        ),
        migrations.AddField(
            model_name='evaluadorproyecto',
            name='modificado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='creado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, verbose_name='fecha de modificación'),
        ),
        migrations.AddField(
            model_name='laboral',
            name='modificado_por',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por'),
        ),
    ]
