# Generated by Django 3.2 on 2021-12-03 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0003_auto_20211203_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdjuntoAsesorTesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(choices=[('laboral', 'Laboral'), ('docente', 'Docente'), ('evaluador_proyecto', 'Evaluador de proyecto'), ('asesor_tesis', 'Asesor de tesis')], max_length=45)),
                ('asesor_tesis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia.asesortesis')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoDocente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(choices=[('laboral', 'Laboral'), ('docente', 'Docente'), ('evaluador_proyecto', 'Evaluador de proyecto'), ('asesor_tesis', 'Asesor de tesis')], max_length=45)),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia.docente')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoEvaluadorProyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(choices=[('laboral', 'Laboral'), ('docente', 'Docente'), ('evaluador_proyecto', 'Evaluador de proyecto'), ('asesor_tesis', 'Asesor de tesis')], max_length=45)),
                ('evaluador_proyecto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia.evaluadorproyecto')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoLaboral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_documento', models.CharField(choices=[('laboral', 'Laboral'), ('docente', 'Docente'), ('evaluador_proyecto', 'Evaluador de proyecto'), ('asesor_tesis', 'Asesor de tesis')], max_length=45)),
                ('laboral', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='experiencia.laboral')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='DocumentoAdjunto',
        ),
    ]
