# Generated by Django 3.2 on 2021-12-03 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0004_auto_20211203_1246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjuntoasesortesis',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='adjuntodocente',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='adjuntoevaluadorproyecto',
            name='tipo_documento',
        ),
        migrations.RemoveField(
            model_name='adjuntolaboral',
            name='tipo_documento',
        ),
    ]
