# Generated by Django 3.2 on 2021-12-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0005_auto_20211203_1248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='docente',
            old_name='traja_actualmente',
            new_name='trabaja_actualmente',
        ),
    ]
