# Generated by Django 3.2 on 2021-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0006_rename_traja_actualmente_docente_trabaja_actualmente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluadorproyecto',
            name='presupuesto_proyecto',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Presupuesto total del proyecto formulado/evaluado'),
        ),
        migrations.AlterField(
            model_name='evaluadorproyecto',
            name='tipo_proyecto_formulado',
            field=models.CharField(choices=[('incentivos_tributarios', 'Incentivos tributarios'), ('pasantias_misiones', 'Pasantías y/o misiones'), ('desarrollo_industrial', 'Proyecto de desarrollo industrial'), ('equipamiento_cientifico', 'Proyectos de equipamiento científico/tecnológico'), ('extensionismo_tecnologico', 'Proyectos de extensionismo tecnológico'), ('innovacion', 'Proyectos de Innovación'), ('inversion_publica_snip', 'Proyectos de inversión pública-SNIP'), ('investigacion_aplicada', 'Proyectos de investigación aplicada'), ('investigacion_basica', 'Proyectos de investigación básica'), ('transferencia_tecnologia', 'Proyectos de transferencia tecnológica'), ('otros', 'Otros')], max_length=45, verbose_name='Tipo de proyecto formulado/evaluado'),
        ),
    ]
