# Generated by Django 3.2 on 2022-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiencia', '0007_auto_20211231_0722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntoasesortesis',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='adjuntodocente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='adjuntoevaluadorproyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='adjuntolaboral',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='docente',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='evaluadorproyecto',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='laboral',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
    ]
