# Generated by Django 3.2 on 2021-11-27 11:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('tipo_contrato', models.CharField(choices=[('docente', 'Docente'), ('administrativo', 'Administrativo'), ('registrador', 'Registrador'), ('autoridad', 'Autoridad')], max_length=15, verbose_name='Tipo de contrato')),
                ('categoria', models.CharField(choices=[('auxiliar', 'Auxiliar'), ('asociado', 'Asociado'), ('principal', 'Principal')], max_length=15, verbose_name='Categoria')),
                ('dedicacion', models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('tiempo_parcial', 'Tiempo parcial')], max_length=15, verbose_name='Dedicación')),
                ('fecha_nacimiento', models.DateField(verbose_name='Fecha de nacimiento')),
                ('nacionalidad', models.CharField(max_length=45, verbose_name='Nacionalidad')),
                ('direccion', models.CharField(max_length=200, verbose_name='Dirección')),
                ('correo_institucional', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('ubigeo_departamento', models.CharField(max_length=2, verbose_name='Departamento')),
                ('ubigeo_provincia', models.CharField(max_length=4, verbose_name='Provincia')),
                ('ubigeo_distrito', models.CharField(max_length=6, verbose_name='Distrito')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=45, verbose_name='Código')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre')),
                ('facultad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('tipo_documento', models.CharField(choices=[('01', 'DNI'), ('03', 'CE'), ('02', 'Pasaporte'), ('04', 'Cédula de identidad')], default='01', max_length=2, verbose_name='Tipo de documento')),
                ('numero_documento', models.CharField(max_length=15, verbose_name='Número de documento')),
                ('sexo', models.CharField(choices=[('2', 'Femenino'), ('1', 'Masculino')], max_length=2, verbose_name='Sexo')),
                ('nombres', models.CharField(blank=True, max_length=120, null=True, verbose_name='Nombre(s)')),
                ('apellido_paterno', models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=120, null=True, verbose_name='Apellido materno')),
                ('celular', models.CharField(blank=True, max_length=50, null=True)),
                ('correo_personal', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.EmailValidator()])),
                ('tipo_persona', models.CharField(choices=[('docente', 'Docente'), ('administrativo', 'Administrativo'), ('registrador', 'Registrador'), ('autoridad', 'Autoridad')], max_length=25)),
                ('es_activo', models.BooleanField(default=True)),
                ('departamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.departamento')),
            ],
            options={
                'ordering': ['apellido_paterno'],
                'unique_together': {('tipo_documento', 'numero_documento')},
            },
        ),
    ]
