# Generated by Django 3.2 on 2021-11-30 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='datosgenerales',
            name='orcid',
            field=models.CharField(blank=True, max_length=45, null=True, verbose_name='ORCID'),
        ),
        migrations.AddField(
            model_name='datosgenerales',
            name='persona',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='persona.departamento'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='tipo_contrato',
            field=models.CharField(choices=[('contratado', 'Contratado'), ('nombrado', 'Nombrado')], max_length=15, verbose_name='Tipo de contrato'),
        ),
    ]
