# Generated by Django 3.2 on 2021-11-30 17:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0003_auto_20211130_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='persona',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
