# Generated by Django 3.2 on 2022-01-26 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_datosgenerales_persona'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='ruta_foto',
            field=models.FileField(blank=True, null=True, upload_to='foto'),
        ),
    ]
