# Generated by Django 3.2 on 2022-02-25 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_catalogoidiomas'),
        ('persona', '0006_persona_resumen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='nacionalidad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais'),
        ),
    ]
