# Generated by Django 3.2 on 2022-06-28 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20220627_2056'),
        ('persona', '0007_alter_datosgenerales_nacionalidad'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegiatura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('sede', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sede')),
                ('codigo_colegiatura', models.CharField(max_length=15, verbose_name='Código')),
                ('estado_colegiatura', models.BooleanField(choices=[('1', 'Habilitado'), ('0', 'Inhabilitado')], default='1', verbose_name='Estado')),
                ('colegio_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.colegio')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
