# Generated by Django 3.2 on 2022-06-29 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0008_colegiatura'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='colegiatura',
            name='codigo_colegiatura',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='colegio_id',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='estado_colegiatura',
        ),
        migrations.RemoveField(
            model_name='colegiatura',
            name='sede',
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='codigo_colegiado',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='estado_colegiado',
            field=models.BooleanField(choices=[('1', 'Habilitado'), ('0', 'Inhabilitado')], default='1'),
        ),
        migrations.AddField(
            model_name='colegiatura',
            name='sede_colegio',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
