# Generated by Django 3.2 on 2022-06-30 00:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_auto_20220627_2056'),
        ('persona', '0009_auto_20220629_2258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common.colegio'),
        ),
        migrations.AlterField(
            model_name='colegiatura',
            name='persona',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
