# Generated by Django 3.2 on 2022-06-30 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0010_auto_20220630_0000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
