# Generated by Django 3.2 on 2022-06-30 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0011_alter_colegiatura_colegio_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='estado_colegiado',
            field=models.BooleanField(choices=[(True, 'Habilitado'), (False, 'Inhabilitado')], default=True),
        ),
    ]
