# Generated by Django 3.2 on 2022-07-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0012_alter_colegiatura_estado_colegiado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='codigo_colegiado',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Código del colegiado'),
        ),
        migrations.AlterField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Colegio profesional'),
        ),
        migrations.AlterField(
            model_name='colegiatura',
            name='estado_colegiado',
            field=models.BooleanField(choices=[(True, 'Habilitado'), (False, 'Inhabilitado')], default=True, verbose_name='Estado del colegiado'),
        ),
        migrations.AlterField(
            model_name='colegiatura',
            name='sede_colegio',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sede del colegio'),
        ),
    ]
