# Generated by Django 3.2 on 2022-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0013_auto_20220701_0821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='persona',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
    ]
