# Generated by Django 3.2 on 2022-07-01 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_auto_20220701_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='categoria',
            field=models.CharField(choices=[('auxiliar', 'Auxiliar'), ('asociado', 'Asociado'), ('principal', 'Principal'), ('dc_b1', 'DC B1'), ('dc_b2', 'DC B2'), ('dc_a1', 'DC A1'), ('jefe_de_practica', 'Jefe de Practicas'), ('servicio_academico_profesional', 'Servicio Academico Profesional')], max_length=45, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='dedicacion',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('tiempo_parcial', 'Tiempo parcial')], max_length=45, verbose_name='Dedicación'),
        ),
        migrations.AlterField(
            model_name='datosgenerales',
            name='tipo_contrato',
            field=models.CharField(choices=[('contratado', 'Contratado'), ('nombrado', 'Nombrado')], max_length=45, verbose_name='Tipo de contrato'),
        ),
    ]
