# Generated by Django 3.2 on 2022-07-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0015_auto_20220701_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datosgenerales',
            name='dedicacion',
            field=models.CharField(choices=[('tiempo_completo', 'Tiempo completo'), ('tiempo_parcial', 'Tiempo parcial'), ('dedicacion_exclusiva', 'Dedicación Exclusiva')], max_length=45, verbose_name='Dedicación'),
        ),
    ]
