# Generated by Django 3.2 on 2022-07-21 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_persona_ruc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
        ),
        migrations.AlterUniqueTogether(
            name='colegiatura',
            unique_together={('codigo_colegiado',)},
        ),
    ]
