# Generated by Django 3.2 on 2022-07-21 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0018_auto_20220721_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persona.persona'),
        ),
    ]
