# Generated by Django 3.2 on 2022-07-22 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0019_alter_colegiatura_persona'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='colegiatura',
            unique_together={('colegio_profesional', 'sede_colegio', 'codigo_colegiado', 'estado_colegiado')},
        ),
    ]
