# Generated by Django 3.2 on 2022-07-22 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_merge_20220628_0808'),
        ('persona', '0020_alter_colegiatura_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.ForeignKey(blank=True, max_length=5, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.colegio', verbose_name='Colegio profesional'),
        ),
    ]
