# Generated by Django 3.2 on 2022-07-22 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0021_alter_colegiatura_colegio_profesional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='colegiatura',
            name='colegio_profesional',
            field=models.CharField(blank=True, max_length=5, null=True, verbose_name='Colegio profesional'),
        ),
    ]
