# Generated by Django 3.2 on 2022-02-15 08:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0005_persona_ruta_foto'),
        ('common', '0003_catalogoidiomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('categoria_trabajo', models.CharField(choices=[('publicacion', 'Publicación'), ('conferencia', 'Conferencia'), ('propiedad_intelectual', 'Propiedad intelecutal'), ('otro', 'Otro')], max_length=45, verbose_name='Categoria de trabajo')),
                ('tipo_obra', models.CharField(choices=[('articulo_boletin', 'Artículo boletín'), ('articulo_revista_cientifica', 'Artículo en revista científica'), ('articulo_magazine', 'Artículo magazine'), ('articulo_periodico', 'Artículo periódico'), ('capitulo_libro', 'Capítulo de libro'), ('dissertacion', 'Dissertación'), ('documento_trabajo', 'Documento de trabajo'), ('entrada_diccionario', 'Entrada de diccionario'), ('entrada_enciclopedia', 'Entrada Enciclopedia/Enciclopedia'), ('fasciculo', 'Fascículo'), ('herramienta_investigacion', 'Herramienta de investigación'), ('libro', 'Libro'), ('libro_editado', 'Libro editado'), ('manual', 'Manual'), ('prefacion_epilogo', 'Prefacio, Epílogo'), ('publicacion_estudiantil_supervisada', 'Publicación estudiantil supervisada'), ('recurso_linea', 'Recurso en línea'), ('reporte', 'Reporte'), ('resena_libro', 'Reseña de libro'), ('test', 'Test'), ('traduccion', 'Traducción'), ('website', 'Website')], max_length=45, verbose_name='Tipo de obra')),
                ('funcion', models.CharField(choices=[('autor', 'Autor'), ('cesionario', 'Cesionario'), ('coinventor', 'Co-inventor'), ('coinvestigador', 'Co-investigador'), ('editor', 'Co-investigador'), ('estudiante_posgrado', 'Estudiante de posgrado'), ('investigador_post_doctoral', 'Investigador postdoctoral'), ('investigador_principal', 'Investigador principal'), ('jefe_traductor', 'Jefe o traductor'), ('otro_inventor', 'Otro inventor'), ('personal_apoyo', 'Personal de apoyo')], max_length=45, verbose_name='Función')),
                ('titulo', models.CharField(max_length=250, verbose_name='Título')),
                ('sub_titulo', models.CharField(max_length=250, verbose_name='Sub-Título')),
                ('revista', models.CharField(max_length=250, verbose_name='Revista')),
                ('volumen', models.PositiveIntegerField(blank=True, null=True)),
                ('fasciculo', models.PositiveIntegerField(blank=True, null=True)),
                ('rango_paginas', models.CharField(max_length=45, verbose_name='Rango de páginas')),
                ('fecha_publicacion', models.DateField()),
                ('tipo_cita', models.CharField(choices=[('apa', 'APA'), ('bibtext', 'BIBTEXT'), ('chicago', 'CHICAGO'), ('harvard', 'HARVARD'), ('ieee', 'IEEE'), ('mla', 'MLA'), ('ris', 'RIS'), ('sin_especificar', 'SIN ESPECIFICAR'), ('vancouver', 'VANCOUVER')], max_length=45, verbose_name='Tipo de cita')),
                ('cita', models.CharField(max_length=250, verbose_name='Cita')),
                ('descripcion', models.CharField(max_length=250, verbose_name='Descripción')),
                ('orden_autoria', models.CharField(choices=[('autor', 'Autor'), ('co_autor', 'Coautor')], max_length=10, verbose_name='Orden autoría')),
                ('autor', models.CharField(max_length=100, verbose_name='Autor')),
                ('pais_publicacion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoCientifica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tipo_obra', models.CharField(choices=[('articulo_boletin', 'Artículo boletín'), ('articulo_revista_cientifica', 'Artículo en revista científica'), ('articulo_magazine', 'Artículo magazine'), ('articulo_periodico', 'Artículo periódico'), ('capitulo_libro', 'Capítulo de libro'), ('dissertacion', 'Dissertación'), ('documento_trabajo', 'Documento de trabajo'), ('entrada_diccionario', 'Entrada de diccionario'), ('entrada_enciclopedia', 'Entrada Enciclopedia/Enciclopedia'), ('fasciculo', 'Fascículo'), ('herramienta_investigacion', 'Herramienta de investigación'), ('libro', 'Libro'), ('libro_editado', 'Libro editado'), ('manual', 'Manual'), ('prefacion_epilogo', 'Prefacio, Epílogo'), ('publicacion_estudiantil_supervisada', 'Publicación estudiantil supervisada'), ('recurso_linea', 'Recurso en línea'), ('reporte', 'Reporte'), ('resena_libro', 'Reseña de libro'), ('test', 'Test'), ('traduccion', 'Traducción'), ('website', 'Website')], max_length=45, verbose_name='Tipo de obra')),
                ('tipo_documento_adjunto', models.CharField(choices=[('revision_pares', 'Revisión de pares'), ('constancia_resultado_investigacion', 'Constancia de resultados de investigación')], max_length=45, verbose_name='Tipo de documento adjunto')),
                ('cientifica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='produccion.cientifica')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
