# Generated by Django 3.2 on 2022-02-15 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cientifica',
            name='tipo_congreso',
            field=models.CharField(blank=True, choices=[('nacional', 'nacional'), ('internacional', 'internacional')], max_length=45, null=True, verbose_name='Tipo de congreso'),
        ),
        migrations.AlterField(
            model_name='cientifica',
            name='cita',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='Cita'),
        ),
        migrations.AlterField(
            model_name='cientifica',
            name='tipo_cita',
            field=models.CharField(blank=True, choices=[('apa', 'APA'), ('bibtext', 'BIBTEXT'), ('chicago', 'CHICAGO'), ('harvard', 'HARVARD'), ('ieee', 'IEEE'), ('mla', 'MLA'), ('ris', 'RIS'), ('sin_especificar', 'SIN ESPECIFICAR'), ('vancouver', 'VANCOUVER')], max_length=45, null=True, verbose_name='Tipo de cita'),
        ),
    ]
