# Generated by Django 3.2 on 2022-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produccion', '0002_auto_20220215_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adjuntocientifica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
        migrations.AlterField(
            model_name='cientifica',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
    ]
