# Generated by Django 3.2 on 2022-01-17 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0004_alter_datosgenerales_persona'),
        ('common', '0002_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Universitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('grado_obtenido', models.CharField(choices=[('doctorado', 'DOCTORADO'), ('magister', 'MAGISTER'), ('licenciado_titulo', 'LICENCIADO/TÍTULO'), ('bachiller', 'BACHILLER'), ('segunda_especialidad', 'SEGUNDA ESPECIALIDAD')], max_length=45, verbose_name='Grado Obtenido')),
                ('nombre_grado', models.CharField(max_length=250, verbose_name='Nombre Título/Grado')),
                ('facultad', models.CharField(max_length=250, verbose_name='Facultad')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('centro_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('pais_estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Tecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre_carrera', models.CharField(max_length=250, verbose_name='Nombre de la carrera')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha fin')),
                ('centro_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Complementaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('capacitacion_complementaria', models.CharField(max_length=250, verbose_name='Capacitación Complementaria')),
                ('frecuencia', models.CharField(choices=[('horas', 'HORAS'), ('dias', 'DIAS'), ('meses', 'MESES'), ('anios', 'AÑOS')], max_length=45, verbose_name='Frecuencia')),
                ('cantidad', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('centro_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('pais_estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoUniversitaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('universitaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.universitaria')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoTecnico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('tecnico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.tecnico')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoComplementaria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('complementaria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.complementaria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
