# Generated by Django 3.2 on 2022-10-23 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0023_alter_colegiatura_colegio_profesional'),
        ('common', '0006_merge_20220628_0808'),
        ('formacion', '0002_auto_20220701_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('denominacion', models.CharField(max_length=250, verbose_name='Denominación de la Maestría')),
                ('duracion', models.PositiveIntegerField(verbose_name='Duración (en Meses)')),
                ('fecha_inicio', models.DateField(blank=True, null=True, verbose_name='Fecha inicio')),
                ('fecha_fin', models.DateField(blank=True, null=True, verbose_name='Fecha fin')),
                ('modalidad', models.CharField(choices=[('presencial', 'PRESENCIAL'), ('virtual', 'VIRTUAL')], max_length=45, verbose_name='Modalidad')),
                ('centro_estudios', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('pais_estudios', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.ubigeopais')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdjuntoMaestria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='creado por')),
                ('modificado_por', models.CharField(blank=True, editable=False, max_length=20, null=True, verbose_name='modificado por')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, null=True, verbose_name='fecha de creación')),
                ('fecha_modificacion', models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre del documento')),
                ('ruta', models.TextField(max_length=500, verbose_name='Ruta del documento')),
                ('maestria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formacion.maestria')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
