# Generated by Django 3.2 on 2021-11-29 17:19

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UbigeoDepartamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_departamento', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')], verbose_name='Código Ubigeo Departamento - RENIEC')),
                ('cod_ubigeo_inei_departamento', models.CharField(max_length=2, validators=[django.core.validators.RegexValidator(message='Numero de 2 digitos', regex='^[0-9]{2}$')], verbose_name='Código Ubigeo Departamento - INEI')),
                ('ubigeo_departamento', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Departamento')),
            ],
            options={
                'verbose_name_plural': '3. Ubigeo Departamentos',
            },
        ),
        migrations.CreateModel(
            name='UbigeoPais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alpha3', models.CharField(blank=True, max_length=3, null=True)),
                ('alpha2', models.CharField(blank=True, max_length=2, null=True)),
                ('cod_ubigeo_reniec_pais', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Numero de 1 o 3 digitos', regex='^[0-9]{1,3}$')], verbose_name='Código Ubigeo Pais - RENIEC')),
                ('cod_ubigeo_inei_pais', models.CharField(max_length=3, validators=[django.core.validators.RegexValidator(message='Numero de 1 o 3 digitos', regex='^[0-9]{1,3}$')], verbose_name='Código Ubigeo Pais - INEI')),
                ('ubigeo_pais', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Pais')),
                ('cod_telefono', models.CharField(blank=True, max_length=10, null=True, verbose_name='Código Teléfono')),
            ],
            options={
                'verbose_name_plural': '2. Ubigeo Paises',
            },
        ),
        migrations.CreateModel(
            name='UbigeoProvincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_provincia', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Numero de 4 digitos', regex='^[0-9]{4}$')], verbose_name='Código Ubigeo Provincia - RENIEC')),
                ('cod_ubigeo_inei_provincia', models.CharField(max_length=4, validators=[django.core.validators.RegexValidator(message='Numero de 4 digitos', regex='^[0-9]{4}$')], verbose_name='Código Ubigeo Provincia - INEI')),
                ('ubigeo_provincia', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Provincia')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeoprovincia_departamento', to='common.ubigeodepartamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeoprovincia_pais', to='common.ubigeopais')),
            ],
            options={
                'verbose_name_plural': '4. Ubigeo Provincias',
            },
        ),
        migrations.CreateModel(
            name='UbigeoDistrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_ubigeo_reniec_distrito', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Numero de 6 digitos', regex='^[0-9]{6}$')], verbose_name='Código Ubigeo Distrito - RENIEC')),
                ('cod_ubigeo_inei_distrito', models.CharField(max_length=6, validators=[django.core.validators.RegexValidator(message='Numero de 6 digitos', regex='^[0-9]{6}$')], verbose_name='Código Ubigeo Distrito - INEI')),
                ('ubigeo_distrito', models.CharField(max_length=100, verbose_name='Nombre Ubigeo Distrito')),
                ('l_inf', models.CharField(blank=True, max_length=15, null=True)),
                ('l_sup', models.CharField(blank=True, max_length=15, null=True)),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeodistrito_departamento', to='common.ubigeodepartamento')),
                ('pais', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeodistrito_pais', to='common.ubigeopais')),
                ('provincia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeodistrito_provincia', to='common.ubigeoprovincia')),
            ],
            options={
                'verbose_name_plural': '5. Ubigeo Distritos',
            },
        ),
        migrations.AddField(
            model_name='ubigeodepartamento',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='common_ubigeodepartamento_pais', to='common.ubigeopais'),
        ),
    ]
