# Generated by Django 3.2 on 2021-12-02 21:15

import apps.common.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=11, validators=[apps.common.models.validate_ruc])),
                ('name', models.CharField(max_length=200)),
            ],
        ),
    ]
