# Generated by Django 3.2 on 2022-01-21 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_institucion'),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogoIdiomas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=6)),
                ('descripcion', models.CharField(max_length=45)),
            ],
        ),
    ]
