# Generated by Django 3.2 on 2022-06-25 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_catalogoidiomas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ubigeopais',
            name='ubigeo_pais',
            field=models.CharField(max_length=127, verbose_name='Nombre Ubigeo Pais'),
        ),
    ]
