# Generated by Django 3.2 on 2022-06-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_alter_ubigeopais_ubigeo_pais'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colegio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acronym', models.CharField(max_length=50, verbose_name='Acrónimo')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre')),
            ],
        ),
        migrations.AlterField(
            model_name='ubigeopais',
            name='ubigeo_pais',
            field=models.CharField(max_length=100, verbose_name='Nombre Ubigeo Pais'),
        ),
    ]
