# Generated by Django 3.2 on 2022-06-28 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_ubigeopais_ubigeo_pais'),
        ('common', '0005_auto_20220627_2056'),
    ]

    operations = [
    ]
