# Generated by Django 3.2 on 2022-01-21 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0003_catalogoidiomas'),
    ]

    operations = [
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lectura', models.CharField(choices=[('basico', 'BÁSICO'), ('intermedio', 'INTERMEDIO'), ('avanzado', 'AVANZADO'), ('avanzado_superior', 'AVANZADO SUPERIOR')], max_length=45)),
                ('conversacion', models.CharField(choices=[('basico', 'BÁSICO'), ('intermedio', 'INTERMEDIO'), ('avanzado', 'AVANZADO'), ('avanzado_superior', 'AVANZADO SUPERIOR')], max_length=45)),
                ('escritura', models.CharField(choices=[('basico', 'BÁSICO'), ('intermedio', 'INTERMEDIO'), ('avanzado', 'AVANZADO'), ('avanzado_superior', 'AVANZADO SUPERIOR')], max_length=45)),
                ('forma_aprendizaje', models.CharField(choices=[('instituto', 'INSTITUTO'), ('autodidacta', 'AUTODIDACTA'), ('software', 'SOFTWARE'), ('otros', 'OTROS')], max_length=45)),
                ('es_lengua_materna', models.BooleanField(default=False)),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.catalogoidiomas')),
            ],
        ),
    ]
