# Generated by Django 3.2 on 2022-01-21 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_alter_datosgenerales_persona'),
        ('idioma', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idioma',
            name='persona',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
            preserve_default=False,
        ),
    ]
