# Generated by Django 3.2 on 2022-07-01 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idioma', '0003_auto_20220122_0725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idioma',
            name='fecha_modificacion',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='fecha de modificación'),
        ),
    ]
