# Generated by Django 3.2 on 2022-07-01 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0014_auto_20220701_1037'),
        ('login', '0002_alter_user_fecha_modificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
        ),
    ]
