# Generated by Django 3.2 on 2022-06-28 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0007_alter_datosgenerales_nacionalidad'),
        ('common', '0006_merge_20220628_0808'),
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CursoDictado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('escuela', models.CharField(max_length=100)),
                ('curso', models.CharField(max_length=100)),
                ('institucion', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='common.institucion')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.persona')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cursos.semestre')),
            ],
        ),
    ]
