# Generated by Django 3.2 on 2022-07-21 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursodictado'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cursodictado',
            options={'ordering': ['semestre', 'institucion', 'escuela', 'curso']},
        ),
    ]
