# Generated by Django 3.2 on 2022-07-21 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_cursodictado'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResponsabilidadSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=400, verbose_name='Título')),
                ('descripcion', models.TextField(verbose_name='Descripción')),
                ('fecha_inicio', models.DateField(verbose_name='Fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='Fecha de fin')),
                ('lugar', models.CharField(max_length=400, verbose_name='Lugar')),
                ('empresa', models.CharField(blank=True, max_length=400, null=True, verbose_name='Empresa')),
                ('ruc', models.CharField(blank=True, max_length=11, null=True, verbose_name='RUC')),
            ],
            options={
                'ordering': ['fecha_fin', 'titulo'],
            },
        ),
        migrations.AlterModelOptions(
            name='cursodictado',
            options={'ordering': ['semestre', 'institucion', 'escuela', 'curso']},
        ),
    ]
