# Generated by Django 3.2 on 2022-07-21 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0017_persona_ruc'),
        ('cursos', '0005_alter_responsabilidadsocial_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='responsabilidadsocial',
            name='persona',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='persona.persona'),
        ),
    ]
