# Generated by Django 3.2 on 2022-07-22 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_alter_cursodictado_options'),
        ('cursos', '0006_responsabilidadsocial_persona'),
    ]

    operations = [
    ]
